uploads = []
generated = []

[[outputs]]
id = "4YthE2st1Nn9VkMYz20Ij"
uri = "file://artifacts/clinic-website/public/images/doctor.jpg"
type = "image"
title = "professional indian male doctor in clinic realistic premium"

[[outputs]]
id = "w-v4LRIuhUidEV8OAeOCN"
uri = "file://artifacts/clinic-website/public/images/clinic_1.jpg"
type = "image"
title = "clean modern well-lit luxury medical clinic interior hospital"

[[outputs]]
id = "9ODYOy6LcYy4tHDiKzubH"
uri = "file://artifacts/clinic-website/public/images/clinic_2.jpg"
type = "image"
title = "clean modern well-lit luxury medical clinic interior hospital"

[[outputs]]
id = "bJo42W_dX3gOZg3f6oLNB"
uri = "file://artifacts/clinic-website/public/images/clinic_3.jpg"
type = "image"
title = "clean modern well-lit luxury medical clinic interior hospital"
